apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-bmc
  labels:
    app: nexus
    release: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.bmc.password | default "" | quote }}
